[package]
name = "counter"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Haneul = { git = "https://github.com/GeunhwaJeong/haneul.git", subdir = "crates/haneul-framework/packages/haneul-framework", rev = "framework/testnet" }

[addresses]
counter = "0x0"
